[[manager.prepend_keymap]]
on = ["g", "l"]
run = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on = "l"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<enter>"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "<C-space>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"
