[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<C-space>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/projects/"
desc = "Goto ~/projects/"

[[mgr.prepend_keymap]]
on = ["g", "C"]
run = "cd ~/dotfiles/"
desc = "Goto ~/dotfiles/"
