#!/usr/bin/env bash

# Function to list tmux sessions (unchanged)
zoxide_query() {
  # From https://github.com/ajeetdsouza/zoxide/blob/0f07314d33f635e2fb324c08aa691a597dad2417/src/cmd/query.rs#L94
  export _ZO_FZF_OPTS="--exact --no-sort --bind=ctrl-z:ignore,btab:up,tab:down --cycle --keep-right --border=sharp --info=inline --layout=reverse --tabstop=1 --exit-0"
  # # Added extra
  if [[ -z $TMUX ]]; then
    export _ZO_FZF_OPTS+=" --height 45%"
  else
    export _ZO_FZF_OPTS+=" --tmux 80%,40%"
  fi
  zoxide query -i
}

# Get the selected directory or session
selected=$(zoxide_query)

if [[ -z $selected ]]; then
  exit 0
fi

# Extract session name or handle directory selection
if [[ $selected =~ ^[-0-9a-zA-Z._]+$ ]]; then
  # Session name provided, use tmux commands directly
  selected_name=$selected
else
  # Directory chosen, generate session name based on directory
  selected_name=$(basename "$selected" | tr . _)
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
  tmux attach -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
